### ISSUE TITLE
Queries about usage

### ISSUE THREAD

**Issue by HarishTeens** [Thomascogez/react-picture-in-picture#27]
1. Can this be integrated for an Agora Video Element?
2. So once it goes into PIP mode, can we update the screen so that they can navigate to other pages as well? just like Youtube? 

But this package does more than Youtube as it lets you play videos on top of all applications, that's just dope 🚀

**Comment by Thomascogez** [comment]
Hey, It look like Agora is using IFrame for implementing their video element.
Since this package use native PIP I don't know if this is possible to use it in this case.
Yes, you can keep the PIP mode active when users are navigating between pages, you will need it to declare it at the top node of your application

**Comment by HarishTeens** [comment]
1. I see, haven't tried it with Agora yet. Will let you know as I'm planning to do that soon. 
2. Yes thanks that would work 😁
